version: '3.9'

services:
    database:
      container_name: mysqldb
      image: mysql:5.7
      environment:
        - MYSQL_DATABASE=test
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ROOT=root
      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
      ports:
          - '3307:3306'
      volumes:
        #- "./database/config/mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
        - "askin-database-volume:/var/lib/mysql"
        #- "./database/init/script-creates.sql:/docker-entrypoint-initdb.d/1.sql"
        #- "./database/init/script-inserts.sql:/docker-entrypoint-initdb.d/2.sql"
      networks:
        - askin-bridge
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10

volumes:
  askin-database-volume:

networks:
  askin-bridge:
    driver: bridge